name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Substitua por 'master' se o seu branch principal for chamado de 'master'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2  # Esta ação verifica o repositório em seu commit mais recente no branch especificado acima

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # A versão do Node.js que você quer usar

      - name: Install Dependencies
        run: npm install  # Este comando instala dependências baseado no arquivo 'package.json'

      - name: Build
        run: npm run build  # Este comando cria os arquivos para publicação (substitua com o seu comando de build se diferente)

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7  # Esta ação faz o deploy dos seus arquivos para o GitHub Pages
        with:
          branch: gh-pages  # Este é o branch onde o GitHub Pages espera encontrar seu site
          folder: build  # O diretório que a etapa de build gera (pode ser diferente dependendo do seu gerador de site estático, por exemplo, 'public' para alguns projetos)
          clean: true  # Este flag é usado para preservar ou limpar os commits antigos no branch de destino
          token: ${{ secrets.GITHUB_TOKEN }}  # Você não precisa criar um token pessoal para acessar o repositório já que o GitHub Actions fornece um token automático
